### ISSUE TITLE
invalid option --c

### ISSUE THREAD

**Issue by lonelykid** [st42/termux-sudo#12]
/system/xbin/su: invalid option --c
Not working on my phone

**Comment by st42** [comment]
The sudo script doesn't use `--c`. It uses `-c`. If you meant `-c`, you must have a non-standard su binary. `-c` is a normal option. Type `su --help` and see if your su binary has this option. If not, sudo will not work.

**Comment by lonelykid** [comment]
Thank you. I meant I used su -c, but it doesn't work. There isn't any help information. Yes, I'm not using the standard android version. I guess the manufacturer modified the su binary.
