### ISSUE TITLE
can not work with Magisk SU.

### ISSUE THREAD

**Issue by DCMMC** [st42/termux-sudo#13]
my terms version is 0.53, Android version is AOSP 7.1.2, using Magisk SU.
when I install termux-sudo then type sudo su, I get this error:
```
$ sudo su
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7153 Aborted                 $SU -c "$MOUNT_RW"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7155 Aborted                 $SU -c "mkdir $ROOT_HOME"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7158 Aborted                 $SU -c "chmod 700 $ROOT_HOME"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7161 Aborted                 $SU -c "echo -e $BASHRC > $ROOT_HOME/.bashrc"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7164 Aborted                 $SU -c "chmod 700 $ROOT_HOME/.bashrc"
CANNOT LINK EXECUTABLE "/sbin/su": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
/data/data/com.termux/files/usr/bin/sudo: line 65:  7167 Aborted                 $SU -c "$MOUNT_RO"

```

**Comment by st42** [comment]
This is an issue with Termux and android 7.1.1 and later. sudo is just a bash script that mimics the behavior of the linux sudo binary. This is an issue for the developer of Termux.

**Comment by DCMMC** [comment]
Oh thanks, i will comment an issue to Termux.

**Comment by st42** [comment]
I have attempted to fix this within termux-sudo. It may just be a work around at the moment, but give it a try as I have no way to test this fix myself. I am reopening this issue until I get feedback on this latest commit.

**Comment by st42** [comment]
I am re-closing this issue because it appears that this issue with 7.1.1+ will have to fixed in Termux.

**Comment by jdgregson** [comment]
For what its worth I am only seeing this issue when running Magisk SU. I have two rooted devices, one with Magisk and one with SuperSU. Magisk has these errors while SuperSU does not. I have customized my termux-sudo script on the Magisk device and now only see one of these error lines when using termux-sudo. I can share my changes if anyone is interested, but they may be device-specific.
