### ISSUE TITLE
Easier installation

### ISSUE THREAD

**Issue by T-vK** [st42/termux-sudo#17]
I usually install sudo like this: 

``` bash
pkg install -y wget ncurses-utils && wget https://raw.githubusercontent.com/st42/termux-sudo/master/sudo -N -O /data/data/com.termux/files/usr/bin/sudo && chmod +x /data/data/com.termux/files/usr/bin/sudo
```

I think it would be helpful to add this to the Readme.

**Comment by st42** [comment]
While this may be quicker, if no errors occur, it may cause confusion if an error does occurs. I intend to leave it as is so that each stage of the installation can either succeed or produce an error. Errors are easier to handle if you are only dealing with one command at a time.
