### ISSUE TITLE
sshd .ssh folder location for root?

### ISSUE THREAD

**Issue by kaefert** [st42/termux-sudo#19]
Hello!

I stumbled upon your termux-sudo script coming from this termux issue:
https://github.com/termux/termux-app/issues/61

What I want is to run openssh `sshd` as root, so that I can use the included sftp-server to browse the whole directory tree of my android device (A Zidoo X8 mediaplayer).

Using your script to open a root terminal makes the shell find the `sshd` binary, but I can't connect to it and I'm guessing it is because the `authorized_keys` file is not used.

I copied my `.ssh` directory with the `authorized_keys` file from `/data/data/com.termux/files/home/.ssh` into `/data/data/com.termux/files/home/.suroot/.ssh` since that is what is printed by `pwd` after running `cd ~`, but still it won't allow me to connect to it.

Can you help me? Thanks!

**Comment by kaefert** [comment]
ah I think I found something. I ran my root sshd instance with the -d parameter and found the following error is printed:
`Authentication refused: bad ownership or modes for file /data/data/com.termux/files/home/.ssh/authorized_keys`

**Comment by kaefert** [comment]
okey so I tried several directories but I always failed somewhere on the `ownership or modes for` some parent directory. The last directory I tried was `/storage/termux_root/.ssh/authorized_keys` which fails because of the permissions of the root directory. I'm unsure what I could break if I change those...

**Comment by reancool** [comment]
bad ownership, me too  ,is there new method? finally ,i use StrictModes no.
