### ISSUE TITLE
the parameter is not available

### ISSUE THREAD

**Issue by breadbread1984** [st42/termux-sudo#5]
su complains that unknown option -- preserve-environment. is there any work around.

**Comment by st42** [comment]
Your su binary wasn't compiled to have this option. Edit the last line of the sudo script and remove
 `--preserve-environment`
It may not be absolutely necessary in your case.

**Comment by st42** [comment]
@breadbread1984 I added a check for the
`--preserve-environment`
su binary option in the latest commit.
