### ISSUE TITLE
didn't create the .bashrc w/ fixed library path statement

### ISSUE THREAD

**Issue by OpnSrcConstruction** [st42/termux-sudo#9]
tested on my N72012 tablet running cyanogenMod.
I cloned and moved into the repo, then ran the cat command as instructed.
Is there a trick, that might not have yet been documented; that I should know about.
the only root app I want is macchanger. under sudo it still says permission denied and after su - it says command not found. I meant to file this issue sooner, but I blame my ADD.

**Comment by st42** [comment]
@OpnSrcConstruction, It sounds like you forgot to run the 2nd command as stated in [README.md](https://github.com/st42/termux-sudo/blob/master/README.md):
`chmod 700 /data/data/com.termux/files/usr/bin/sudo`
Just to clarify these commands must be run in a Termux terminal.

**Comment by OpnSrcConstruction** [comment]
No I did run the chmod command, but I don't understand how catting a text file into a binary directory, creates a library alias in the .bashrc? I'll try it again though tonight, as I had to reload that tablet. I'll let ya know either way.

**Comment by st42** [comment]
Catting the text (script) file into place is just a way to copy the file and make sure the proper ownership is set. Next we change the permission to 700 so it can only be read, written and executed by the files owner and root.

The `.bashrc` file is created in the root folder `.suroot`  by the sudo script on its first run. `.bashrc` is a hidden file and `.suroot` is a hidden directory and wont be listed normally. To see them use `ls -la`

If you are able to drop to a root shell with `sudo su` , sudo is working properly. If not check the app that controls your su binary. The default for CyanogenMod is in Settings->Privacy->Privacy Guard. You may have to go into the advance menu option and swipe over to the root access section. Make sure Termux and Termux:API are allowed root access.

The permission problem might be with macchanger. You have to take down the network interface before using macchanger and bring it back up aterwards. For example:
`sudo ifconfig wlan0 down`
`sudo macchanger -A wlan0`
`sudo ifconfig wlan0 up`
